name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          my-fullstack-app/frontend/package-lock.json
          my-fullstack-app/backend/package-lock.json
    
    # Backend tests
    - name: Install backend dependencies
      run: npm install
      working-directory: ./my-fullstack-app/backend
    
    - name: Run backend tests
      run: npm test
      working-directory: ./my-fullstack-app/backend
    
    - name: Run backend linting
      run: npm run lint
      working-directory: ./my-fullstack-app/backend
    
    # Frontend tests
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./my-fullstack-app/frontend
    
    - name: Run frontend tests
      run: npm test -- --coverage --watchAll=false
      working-directory: ./my-fullstack-app/frontend
    
    - name: Run frontend linting
      run: npm run lint
      working-directory: ./my-fullstack-app/frontend

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: |
          my-fullstack-app/frontend/package-lock.json
          my-fullstack-app/backend/package-lock.json
    
    # Build backend
    - name: Install backend dependencies
      run: npm install
      working-directory: ./my-fullstack-app/backend
    
    - name: Build backend (if build script exists)
      run: npm run build --if-present
      working-directory: ./my-fullstack-app/backend
    
    # Build frontend
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./my-fullstack-app/frontend
    
    - name: Build frontend for production
      run: npm run build
      working-directory: ./my-fullstack-app/frontend
    
    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: my-fullstack-app/frontend/build/
    
    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: my-fullstack-app/backend/